import json
import os
import sys
from datetime import datetime

from mako.template import Template
from mako.lookup import TemplateLookup

# Phase 1 imports
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from isl.parser import ShellInterface, load as load_isl

from hls_report_parser import HLSReportParser, HLSReportError
from adapter_params import AdapterParameterSelector
from testbench_generator import TestbenchGenerator


GENERATOR_VERSION = "1.0.0"

TEMPLATE_DIR = os.path.join(os.path.dirname(__file__), "templates")


class AdapterGeneratorError(Exception):
    pass


class AdapterGenerator:
    def __init__(self):
        self.template_lookup = TemplateLookup(
            directories=[TEMPLATE_DIR],
            output_encoding="utf-8",
            input_encoding="utf-8",
        )
        self.params_selector = AdapterParameterSelector()
        self.testbench_gen = TestbenchGenerator()

    def generate(
        self,
        isl_path: str,
        hls_report_dir: str,
        output_dir: str = ".",
        module_name: str = "auto_adapter_top",
    ) -> dict:
        if not os.path.exists(isl_path):
            raise AdapterGeneratorError(f"ISL file not found: {isl_path}")
        if not os.path.exists(hls_report_dir):
            raise AdapterGeneratorError(f"HLS report directory not found: {hls_report_dir}")

        os.makedirs(output_dir, exist_ok=True)
        os.makedirs(os.path.join(output_dir, "hdl"), exist_ok=True)
        os.makedirs(os.path.join(output_dir, "sim"), exist_ok=True)

        iface = load_isl(isl_path)
        parser = HLSReportParser()
        hls_sig = parser.parse(hls_report_dir)

        params = self.params_selector.select(
            hls_latency=hls_sig.pipeline_latency or 8,
            shell_clock_mhz=iface.clock_freq,
            hls_clock_mhz=hls_sig.target_freq_mhz or iface.clock_freq,
            data_width=iface.data_width,
            metadata_must_span=iface.protocol_quirks.metadata_must_span_entire_packet,
        )

        # Detect whether the HLS module has TUSER ports on its AXI4-Stream
        # Real HLS modules typically have no TUSER (WUser=0), so TUSER is
        # captured and replayed via the metadata FIFO. Mock modules used
        # in verification may include TUSER for direct pass-through testing.
        params.pass_tuser_to_hls = hls_sig.has_tuser_ports()

        hls_data_width = 512
        in_axis = hls_sig.get_input_axis_port()
        out_axis = hls_sig.get_output_axis_port()
        if in_axis:
            hls_data_width = in_axis.width
        hls_tuser_width = iface.tuser_width

        template_vars = {
            "iface": iface,
            "hls_sig": hls_sig,
            "hls_data_width": hls_data_width,
            "hls_tuser_width": hls_tuser_width,
            "params": params,
            "module_name": module_name,
            "generator_version": GENERATOR_VERSION,
            "generated_date": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        }

        # Render adapter RTL
        template = self.template_lookup.get_template("adapter_top.sv")
        rtl_output = template.render(**template_vars)

        rtl_path = os.path.join(output_dir, "hdl", f"{module_name}.sv")
        with open(rtl_path, "w") as f:
            if isinstance(rtl_output, bytes):
                f.write(rtl_output.decode("utf-8"))
            else:
                f.write(rtl_output)

        # Generate cocotb testbench
        tb_path = os.path.join(output_dir, "sim", "test_auto_adapter.py")
        self.testbench_gen.generate(iface, params, hls_sig, tb_path)

        # Generate Vivado Tcl integration script
        tcl_path = os.path.join(output_dir, f"insert_adapter.tcl")
        self._generate_tcl_script(
            tcl_path, module_name, iface.data_width, iface.tuser_width,
            params
        )

        # Generate adapter summary
        summary_path = os.path.join(output_dir, "adapter_summary.txt")
        self._generate_summary(summary_path, iface, hls_sig, params)

        generated_files = {
            "rtl": rtl_path,
            "testbench": tb_path,
            "tcl": tcl_path,
            "summary": summary_path,
        }

        return generated_files

    def _generate_tcl_script(
        self, path: str, module_name: str,
        data_width: int, tuser_width: int, params
    ):
        content = f"""# AutoAdapter — Vivado IP Integration Script
# Generated by AutoAdapter v{GENERATOR_VERSION}

set adapter_top {module_name}

# Add adapter HDL sources
add_files -norecurse {{ hdl/{module_name}.sv }}

# Set adapter as top module for synthesis
set_property top {module_name} [current_fileset]

# Create block design or connect manually:
# connect the shell's AXI4-Stream output to s_axis_*
# connect the shell's AXI4-Stream input  to m_axis_*
# connect hls_in_* to the HLS core input
# connect hls_out_* to the HLS core output

# Parameter summary:
# C_S_AXIS_TDATA_WIDTH   = {data_width}
# C_S_AXIS_TUSER_WIDTH   = {tuser_width}
# C_METADATA_FIFO_DEPTH  = {params.metadata_fifo_depth}
# C_NUM_REG_SLICES       = {params.num_reg_slices}
# C_PASS_TUSER_TO_HLS    = {int(params.pass_tuser_to_hls)}
"""
        with open(path, "w") as f:
            f.write(content)

    def _generate_summary(self, path: str, iface, hls_sig, params):
        content = f"""AutoAdapter — Adapter Summary
{'=' * 60}
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

Shell Interface:
  Name:     {iface.name}
  Clock:    {iface.clock_freq} MHz
  Data:     {iface.data_width}-bit
  TUSER:    {iface.tuser_width}-bit
  Fields:   {len(iface.tuser_fields)}

HLS Module:
  Name:     {hls_sig.module_name or 'unknown'}
  Latency:  {hls_sig.pipeline_latency or 'unknown'} cycles
  Clock:    {hls_sig.target_freq_mhz or 'unknown'} MHz

Adapter Parameters:
  Metadata FIFO Depth:  {params.metadata_fifo_depth}
  Register Slices:      {params.num_reg_slices}
  TUSER Strategy:       {params.tuser_update_strategy}
  Clock Crossing:       {params.clock_crossing}
  Pass TUSER to HLS:    {params.pass_tuser_to_hls}
"""
        with open(path, "w") as f:
            f.write(content)


def generate(
    isl_path: str,
    hls_report_dir: str,
    output_dir: str = "output",
    module_name: str = "auto_adapter_top",
) -> dict:
    gen = AdapterGenerator()
    return gen.generate(isl_path, hls_report_dir, output_dir, module_name)


def main():
    import argparse
    parser = argparse.ArgumentParser(
        description="AutoAdapter — HLS-to-Shell Adapter Generator"
    )
    parser.add_argument("isl", help="Path to ISL specification file (.json)")
    parser.add_argument("hls_report", help="Path to HLS synthesis report directory or file")
    parser.add_argument("-o", "--output", default="output", help="Output directory")
    parser.add_argument("-m", "--module-name", default="auto_adapter_top", help="Top module name")
    args = parser.parse_args()

    try:
        files = generate(args.isl, args.hls_report, args.output, args.module_name)
        print(f"AutoAdapter generation complete!")
        print(f"  RTL:        {files['rtl']}")
        print(f"  Testbench:  {files['testbench']}")
        print(f"  Tcl Script: {files['tcl']}")
        print(f"  Summary:    {files['summary']}")
    except (AdapterGeneratorError, HLSReportError, FileNotFoundError) as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
